# Generated by Django 5.2.12 on 2026-04-02 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Optional profile picture",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                (
                    "study_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Current consecutive-day study streak"
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="All-time longest streak"
                    ),
                ),
                (
                    "last_study_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of the most recent study activity",
                        null=True,
                    ),
                ),
                (
                    "target_exam_date",
                    models.DateField(
                        blank=True,
                        help_text="User's planned exam date — used to surface urgency cues",
                        null=True,
                    ),
                ),
                (
                    "exam_readiness_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Weighted confidence score 0–100 across all four domains",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_studied_topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Most recently studied topic — used for 'Continue' button",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="learning.topic",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
            },
        ),
    ]
