# Generated by Django 5.2.12 on 2026-04-02 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mc", "Multiple Choice"),
                            ("ms", "Multi-Select"),
                            ("tf", "True / False"),
                            ("fib", "Fill in the Blank"),
                            ("code_output", "Code Output Prediction"),
                            ("short", "Short Answer / Explanation"),
                        ],
                        default="mc",
                        max_length=15,
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="The question prompt shown to the user"),
                ),
                (
                    "code_snippet",
                    models.TextField(
                        blank=True,
                        help_text="Optional Python code block displayed with the question",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Shown to the user after they answer"
                    ),
                ),
                (
                    "hint",
                    models.TextField(
                        blank=True, help_text="Optional nudge (costs a hint token)"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "pcep_objective",
                    models.CharField(
                        blank=True,
                        help_text="Objective code inherited from the topic, e.g. 2.2.1",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-populated from topic.domain — do not set manually",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.domain",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.topic",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "questions",
                "ordering": ["topic__domain__order", "topic__order", "difficulty"],
            },
        ),
        migrations.CreateModel(
            name="AnswerChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Per-choice explanation shown after answering (why right or wrong)",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="quizzes.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("topic", "Topic Quiz"),
                            ("domain", "Domain Quiz"),
                            ("exam", "Full Exam Mode"),
                            ("review", "Mistake Review"),
                        ],
                        default="topic",
                        max_length=10,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0, help_text="Percentage correct, 0–100"
                    ),
                ),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                (
                    "is_passed",
                    models.BooleanField(
                        default=False,
                        help_text="True when score >= 70% (PCEP passing threshold)",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_limit_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Wall-clock limit; null means no limit",
                        null=True,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_attempts",
                        to="learning.domain",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_attempts",
                        to="learning.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_answer", models.TextField(blank=True)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "time_taken_seconds",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Seconds spent on this question",
                        null=True,
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quizzes.quizattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="quizzes.question",
                    ),
                ),
                (
                    "selected_choices",
                    models.ManyToManyField(blank=True, to="quizzes.answerchoice"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["answered_at"],
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
