# Generated by Django 5.2.12 on 2026-04-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="mode",
            field=models.CharField(
                choices=[
                    ("topic", "Topic Quiz"),
                    ("domain", "Domain Quiz"),
                    ("mixed", "Mixed Mode"),
                    ("exam", "Full Exam Mode"),
                    ("review", "Mistake Review"),
                ],
                default="topic",
                max_length=10,
            ),
        ),
    ]
