"""Admin for the quizzes app — questions, choices, attempts, and answers."""

from django.contrib import admin

from core.admin_utils import coloured_score
from .models import AnswerChoice, Question, QuizAttempt, UserAnswer


# ── Inline ─────────────────────────────────────────────────────────────────

class AnswerChoiceInline(admin.TabularInline):
    """Row-per-choice table directly under a Question.

    'order' appears first so authors can drag-sort without leaving the page.
    The is_correct checkbox is at the end and turns green via CSS when ticked
    (Django admin does not add colour by default, but the column heading makes
    it obvious which answer is marked correct).
    """
    model = AnswerChoice
    extra = 4          # show four blank rows for a typical MC question
    fields = ("order", "text", "is_correct", "explanation")


# ── Question ───────────────────────────────────────────────────────────────

@admin.register(Question)
class QuestionAdmin(admin.ModelAdmin):
    """Central content-management view for quiz questions.

    The domain filter drills from a high level (which PCEP domain?) down to
    topic and difficulty so a content manager can quickly audit coverage gaps.
    The 'active' toggle lets you draft questions without students seeing them.
    """

    list_display = (
        "text_short", "topic", "domain", "question_type",
        "difficulty", "choice_count", "has_explanation", "is_active",
    )
    list_display_links = ("text_short",)
    list_editable = ("is_active",)
    list_filter = ("domain", "topic", "question_type", "difficulty", "is_active")
    search_fields = ("text", "code_snippet", "explanation", "pcep_objective")
    autocomplete_fields = ("topic",)
    readonly_fields = ("domain", "created_at", "updated_at")
    inlines = [AnswerChoiceInline]

    fieldsets = (
        (None, {
            "fields": ("topic", "domain", "question_type", "difficulty", "pcep_objective"),
            "description": (
                "'domain' is filled in automatically from the chosen topic — "
                "you cannot edit it directly."
            ),
        }),
        ("Question content", {
            "fields": ("text", "code_snippet"),
        }),
        ("Feedback", {
            "fields": ("explanation", "hint"),
            "description": (
                "Explanation is shown to the student after they answer. "
                "Hint is optional and costs a hint token."
            ),
        }),
        ("Status", {
            "fields": ("is_active", "created_at", "updated_at"),
            "classes": ("collapse",),
        }),
    )

    @admin.display(description="Question")
    def text_short(self, obj):
        return obj.text[:90] + ("…" if len(obj.text) > 90 else "")

    @admin.display(description="Choices")
    def choice_count(self, obj):
        n = obj.choices.count()
        correct = obj.choices.filter(is_correct=True).count()
        return f"{n} ({correct}✓)"

    @admin.display(description="Explanation", boolean=True)
    def has_explanation(self, obj):
        return bool(obj.explanation)


# ── QuizAttempt ────────────────────────────────────────────────────────────

@admin.register(QuizAttempt)
class QuizAttemptAdmin(admin.ModelAdmin):
    """Read-only audit view of completed quiz sessions.

    Attempts are generated by the application; instructors should not create
    or edit them directly, so all fields are read-only.
    """

    list_display = (
        "user", "mode", "scope_label", "score_badge",
        "total_questions", "correct_count", "is_passed", "started_at",
    )
    list_filter = ("mode", "is_passed", "domain", "topic")
    search_fields = ("user__username", "user__email")
    readonly_fields = (
        "user", "mode", "topic", "domain", "score", "total_questions",
        "correct_count", "is_passed", "started_at", "finished_at",
        "time_limit_seconds",
    )
    date_hierarchy = "started_at"

    fieldsets = (
        (None, {
            "fields": ("user", "mode", "topic", "domain"),
        }),
        ("Results", {
            "fields": ("score", "total_questions", "correct_count", "is_passed"),
        }),
        ("Timing", {
            "fields": ("started_at", "finished_at", "time_limit_seconds"),
        }),
    )

    def has_add_permission(self, request):
        return False   # attempts are created by the app, not by admins

    @admin.display(description="Scope")
    def scope_label(self, obj):
        if obj.topic:
            return f"Topic: {obj.topic.name}"
        if obj.domain:
            return f"Domain {obj.domain.order}"
        return "Full exam"

    @admin.display(description="Score")
    def score_badge(self, obj):
        return coloured_score(obj.score)


# ── UserAnswer ─────────────────────────────────────────────────────────────

@admin.register(UserAnswer)
class UserAnswerAdmin(admin.ModelAdmin):
    """Detailed per-answer audit trail — useful for spotting tricky questions."""

    list_display = (
        "user", "question_short", "is_correct", "time_taken_seconds", "answered_at",
    )
    list_filter = ("is_correct", "question__domain", "question__topic", "question__difficulty")
    search_fields = ("user__username", "question__text")
    readonly_fields = (
        "attempt", "question", "user", "selected_choices",
        "text_answer", "is_correct", "time_taken_seconds", "answered_at",
    )
    date_hierarchy = "answered_at"

    def has_add_permission(self, request):
        return False

    @admin.display(description="Question")
    def question_short(self, obj):
        return obj.question.text[:70] + ("…" if len(obj.question.text) > 70 else "")
