# Generated by Django 5.2.12 on 2026-04-02 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodingChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(help_text="Problem statement shown to the user"),
                ),
                (
                    "starter_code",
                    models.TextField(
                        blank=True, help_text="Pre-filled skeleton shown in the editor"
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(
                        help_text="Exact stdout the solution must produce for test_input"
                    ),
                ),
                (
                    "test_input",
                    models.TextField(
                        blank=True,
                        help_text="Simulated stdin values fed to input(), one value per line",
                    ),
                ),
                ("hint_1", models.TextField(blank=True)),
                ("hint_2", models.TextField(blank=True)),
                ("hint_3", models.TextField(blank=True)),
                (
                    "solution_code",
                    models.TextField(
                        blank=True,
                        help_text="Reference solution — never exposed to the user",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-populated from topic.domain — do not set manually",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_challenges",
                        to="learning.domain",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_challenges",
                        to="learning.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["topic__domain__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="CodingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_code", models.TextField()),
                (
                    "actual_output",
                    models.TextField(
                        blank=True, help_text="Captured stdout from sandbox"
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("hints_used", models.PositiveSmallIntegerField(default=0)),
                (
                    "time_taken_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Seconds from page load to submission",
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="labs.codingchallenge",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
