# Generated by Django 5.2.12 on 2026-04-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codingattempt",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error traceback if code raised an exception"
            ),
        ),
        migrations.AddField(
            model_name="codingchallenge",
            name="max_attempts_before_reveal",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Show solution explanation after this many failed tries (0 = never auto-reveal)",
            ),
        ),
        migrations.AddField(
            model_name="codingchallenge",
            name="solution_explanation",
            field=models.TextField(
                blank=True,
                help_text="Walkthrough shown after the user solves it (or after max failed attempts)",
            ),
        ),
    ]
